### ISSUE TITLE
Feature request: moderated form that allows easy inserting of data directly

### ISSUE THREAD

**Issue by treaz** [ericalexanderorg/SecurityBreach#10]
instead of this: "Github issues used to queue up findings that need to be added."
I would find it more useful to have a form on the website that allows anyone to add a breach. After that, we would just have to check for correctness and approve. 

It would have some of the workload off the maintainer.

**Comment by ericalexanderorg** [comment]
We need to find a balance between lightweight (little to no infra to maintain), reduced friction on adding data, and data accuracy (to the best of our abilities and based on osint). 

One possible way to do this would be an HTML form in S3 along with a lambda job that submits an MR.

**Comment by treaz** [comment]
how about pr #23?

**Comment by ericalexanderorg** [comment]
I like the idea of the form as a way to reduce intake and categorization friction but I think there's a couple of obstacles to the approach:

- The current UI is deployed as a react app using mostly react-admin. I'm not sure if you can include an HTML page in a react app. It could be recreated using SimpleForm: https://marmelab.com/react-admin/CreateEdit.html#the-simpleform-component
- Posting the JSON back to the user would save some time but it would be better to automate further to the point that it would create a PR. 

Thoughts on this approach?
- Create a new issues template that matches the HTML form and labels the issue intake-to-pr
- Scheduled Github Actions job that runs every X minutes and looks at the intake-to-pr. 
- Simple tests to make sure data is OK and then it creates a PR and links to the issue

**Comment by ericalexanderorg** [comment]
... and issue templates are not as user friendly as I expected. Need to think about how we can go from postback to auto PR with little to no infra to support.

**Comment by ericalexanderorg** [comment]
Created a form as a first step towards ^^. Next step will be to use Github Actions to review new issues and auto-submit a PR if they match new breach JSON. 

https://github.com/ericalexanderorg/SecurityBreach/pull/25

**Comment by treaz** [comment]
@ericalexanderorg the form that you created looks good to time and it first the purpose for the moment. Consider closing this
