### ISSUE TITLE
Brooklyn Hospital Center

### ISSUE THREAD

**Issue by ericalexanderorg** [ericalexanderorg/SecurityBreach#129]
https://www.bleepingcomputer.com/news/security/brooklyn-hospital-loses-patient-data-in-ransomware-attack/

**Comment by ericalexanderorg** [comment]
A ransomware attack hitting several computer systems at the Brooklyn Hospital Center in New York caused permanent loss of some patient's data. The hospital tried to recover the data but all efforts were in vain. The attack occurred in late July but the hospital acknowledged it publicly only last week, following what the institution calls "An exhaustive investigation," and after undertaking "Diligent remediation efforts." "On September 4, 2019, the investigation confirmed that due to the malware, and despite exhaustive efforts by the Hospital to recover the data, certain patient data was unrecoverable." The hospital highlights that the investigation did not find any evidence that the data was exfiltrated from its systems or otherwise misused. In this case, the hospital did not provide any details about the ransomware strain used in the attack or the money demanded by cybercriminals. While the notification to patients indicates that the hospital did not give in to the criminal demands, which is recommended by both the infosec community and law enforcement, it also suggests that Brooklyn Hospital Center did not have a proper backup system implemented.

**Comment by ericalexanderorg** [comment]
ML classification

Motive: Money:Ransomware [Correct]
Actor: Criminal [Correct]
Initial Access: ATT&CK T1078 (Valid Accounts) [Not Correct]

Initial Access should be "?" but the ML was never trained on "?" out of concern it would incorrectly match. May need to train it on "?".

**Comment by treaz** [comment]
What's the threshold for correct, for each tag? Training on "?" may result on more results beings classified as "?"... right?
