### ISSUE TITLE
Documentation: specific hackers

### ISSUE THREAD

**Issue by treaz** [ericalexanderorg/SecurityBreach#43]
Sometimes we get articles that state a specific hacker. E.g. L&M (https://www.vice.com/en_us/article/zmpx4x/hacker-monitor-cars-kill-engine-gps-tracking-apps).
There's no good option for this kind of guy in the tags.actor. We need to decide how to go around it and to document our decision somewhere visible.

Personally, I would find it pity to throw away that information (since we have it), but I also understand that we might not need it for the dashboard.

On the other hand, how useful is it to know that the hacker's name was L&M. Is that traceable, or can someone obtain more information about that hacker? If not, then it's as good as not knowing the hacker name.

@ericalexanderorg what do you think?

**Comment by ericalexanderorg** [comment]
Sounds good. Also think we can stuff more info in tags.actor. There's clear patterns that actors fall into one of three categories: Nation State, Criminal, and Hacktivist. We can stuff more info with no tags using a colon separator. 

This example would be "Hacktivist:L&M". When possible we should adopt [Mitre's group list](https://attack.mitre.org/groups/). Using APT1 as an example we'd have "Nation State:APT1". 

Having that correlation would enable more insight into relationships between actor types, motives, and initial access choices.

**Comment by treaz** [comment]
Sounds good. Should we add another (optional) text field to the creation form. If that field is filled, then we can concat the actor+hacker name (using a colon). Good enough?
