### ISSUE TITLE
NordVPN

### ISSUE THREAD

**Issue by ericalexanderorg** [ericalexanderorg/SecurityBreach#68]
https://twitter.com/hexdefined/status/1185864801261477891

Sounds like

- Somebody got access to one of their containers running openvpn
- The container had both private keys for the endpoint and the CA private keys (not clear why those keys would be there)
- They rotated the keys but didn't disclose the breach

**Comment by treaz** [comment]
https://nordvpn.com/nl/blog/official-response-datacenter-breach/
