### ISSUE TITLE
add number of affected users to schema

### ISSUE THREAD

**Issue by treaz** [ericalexanderorg/SecurityBreach#7]
As a manager,
I want to see how many users were affected by a breach, together with the breach type,
So that I can get an idea of what parts of security to focus on (better prioritization of security tasks)

**Comment by ericalexanderorg** [comment]
Tags can accommodate. 

It would look something like this:


    {
      "entity": "AccuDoc",
      "month": 9,
      "year": 2018,
      "summary": "?",
      "tags": {
        "motive": "?",
        "actor": "?",
        "initial-access": "",
        "impacted-user-count": 1000
      },
      "links": [
        "https://www.reddit.com/r/securitybreach/comments/a23x7h/accudoc_0918/?"
      ]
    },

**Comment by treaz** [comment]
Great, PR submitted
