### ISSUE TITLE
Urls of breaches do not appear in UI

### ISSUE THREAD

**Issue by treaz** [ericalexanderorg/SecurityBreach#8]
I just checked the Australian Emergency Warning System breach in the UI and it doesn not show any URL. The key is populated in the datasource

**Comment by treaz** [comment]
@ericalexanderorg could it be that you haven't deployed the latest version of the app recently? When I run it locally, I can see the links well.

**Comment by ericalexanderorg** [comment]
Deployed. I need to setup a Github Action to deploy the UI on a commit or merge.

**Comment by ericalexanderorg** [comment]
https://github.com/ericalexanderorg/SecurityBreach/issues/11
