### ISSUE TITLE
Feature request: add financial cost of breach to schema

### ISSUE THREAD

**Issue by treaz** [ericalexanderorg/SecurityBreach#9]
As a manager,
I want to see the costs of a security breach,
So that I can include app security in my financial planning

**Comment by ericalexanderorg** [comment]
We can accomodate with a cost tag

It would look like this and wouldn't require a schema change. 

`    {
      "entity": "E-Z Up",
      "month": 10,
      "year": 2018,
      "summary": "Javascript injected in site to steal credit card information",
      "tags": {
        "motive": "Money:Credit Card",
        "actor": "MageCart",
        "initial-access": "A10-Insufficient Logging & Monitoring",
        "cost-usd": 100 
      },
      "links": [
        "https://www.reddit.com/r/securitybreach/comments/ahm9jt/ez_up_1018/?"
      ]
    }`

**Comment by treaz** [comment]
@ericalexanderorg see PR
